fix ncp routing command
zsmartsystems/com.zsmartsystems.zigbee pull request #1197
Opened 2021-01-20 08:02 UTC by mikomarrache

2021-01-20 18:32 UTC, cdjackson requested changes
Thanks @mikomarrache - just a couple of small comments...

2021-01-20 18:32 UTC, cdjackson commented on com.zsmartsystems.zigbee.console.ember/src/main/java/com/zsmartsystems/zigbee/console/ember/EmberConsoleNcpRoutingCommand.java
> +        out.println(String.format("%-15s  %-15s  %-6s  %-15s  %-15s", "Destination", "Next", "Age", "Concentrator", "Status"));
Can we make these a constant since it's used in 2 places (for the title and the data)

2021-01-20 18:32 UTC, cdjackson commented on com.zsmartsystems.zigbee.console.ember/src/main/java/com/zsmartsystems/zigbee/console/ember/EmberConsoleNcpRoutingCommand.java
> +        out.println(String.format("%-6s  %-15s  %-10s  |  %s", "IDX", "Destination", "Closer IDX", "Route"));
Can we make these a constant since it's used in 2 places (for the title and the data)

2021-01-26 07:57 UTC, mikomarrache commented
@cdjackson Hi, I pushed the changes

2021-01-26 08:36 UTC, cdjackson commented
Thanks @mikomarrache

2021-01-26 08:36 UTC, merged